# Generated by Django 3.2.5 on 2021-07-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_card',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
