# Generated by Django 3.2.5 on 2021-07-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='purchases',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
