# Generated by Django 3.2.5 on 2021-07-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_client_purchases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='money_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
