# Generated by Django 3.2.5 on 2021-07-20 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=144)),
                ('presentation', models.CharField(blank=True, max_length=3)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('price_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('price_2', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('price_3', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('brand', models.CharField(blank=True, max_length=32)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.category')),
            ],
        ),
    ]
