# Generated by Django 3.2.5 on 2021-07-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210720_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
