# Generated by Django 3.2.5 on 2021-08-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_sale_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesman',
            name='biggest_sell',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesman',
            name='money_generated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesman',
            name='phone_1',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='salesman',
            name='phone_2',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='salesman',
            name='purchases',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
