# Generated by Django 3.2.5 on 2021-08-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_barcode_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='description',
            field=models.CharField(default='test', max_length=32),
            preserve_default=False,
        ),
    ]
