# Generated by Django 3.2.5 on 2021-08-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_sale_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='product', through='core.ProductSale', to='core.Product'),
        ),
    ]
