# Generated by Django 3.2.5 on 2021-08-08 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210803_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesman',
            name='biggest_sell',
        ),
        migrations.RemoveField(
            model_name='salesman',
            name='money_generated',
        ),
        migrations.RemoveField(
            model_name='salesman',
            name='purchases',
        ),
        migrations.AlterField(
            model_name='productsale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sale'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ManyToManyField(through='core.ProductSale', to='core.Product'),
        ),
        migrations.CreateModel(
            name='SalesmanIndicators',
            fields=[
                ('salesman', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.salesman')),
                ('purchases', models.PositiveIntegerField(default=0)),
                ('money_generated', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('biggest_sale', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sale')),
            ],
        ),
    ]
