# Generated by Django 3.2.5 on 2021-08-10 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210808_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='money_spent',
        ),
        migrations.RemoveField(
            model_name='client',
            name='purchases',
        ),
        migrations.CreateModel(
            name='ClientIndicator',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.client')),
                ('purchases', models.PositiveIntegerField(default=0)),
                ('money_generated', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('biggest_sale', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sale')),
            ],
        ),
    ]
