# Generated by Django 3.2.5 on 2021-08-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_salesman_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
