# Generated by Django 3.2.5 on 2021-08-30 16:37

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210830_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_1',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_2',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_3',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=12),
        ),
    ]
