# Generated by Django 3.2.5 on 2021-08-31 18:13

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210830_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientindicator',
            name='money_generated_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('VES', 'Bolivar Venezolano'), ('USD', 'Dolar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='salesmanindicators',
            name='money_generated_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('VES', 'Bolivar Venezolano'), ('USD', 'Dolar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='clientindicator',
            name='money_generated',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesmanindicators',
            name='money_generated',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=12),
        ),
    ]
