# Generated by Django 3.2.5 on 2022-02-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20220225_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
