# Generated by Django 3.2.5 on 2022-04-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('AD', 'Admin'), ('S', 'Salesman'), ('C', 'Client'), ('N', 'None')], default='N', max_length=2),
        ),
    ]
