# Generated by Django 3.2.5 on 2022-04-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('NONE', 'None'), ('ADMIN', 'Admin'), ('SALESMAN', 'Salesman'), ('CLIENT', 'Client')], default='NONE', max_length=10),
        ),
    ]
