# Generated by Django 3.2.5 on 2022-04-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('NONE', 'None'), ('ADMIN', 'Admin'), ('SALESMAN', 'Salesman'), ('CLIENT', 'Client'), ('SALESMAN_AND_CLIENT', 'Salesman and Client')], default='NONE', max_length=20),
        ),
    ]
