# Generated by Django 3.2.5 on 2022-05-28 13:53

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20220416_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('income_currency', djmoney.models.fields.CurrencyField(choices=[('VES', 'Bolivar Venezolano'), ('USD', 'Dolar')], default='USD', editable=False, max_length=3)),
                ('income', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('income_currency', djmoney.models.fields.CurrencyField(choices=[('VES', 'Bolivar Venezolano'), ('USD', 'Dolar')], default='USD', editable=False, max_length=3)),
                ('income', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(through='core.ProductOrder', to='core.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='salesman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.salesman'),
        ),
    ]
