# Generated by Django 3.2.5 on 2022-05-29 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_ordersale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
